SET SCHEMA IBL_D_SIM;
-- [BKN]
-- 1) BKN_DX_SERVICE_RUN -> service started check
-- 2) BKN_DS_EOD_PARM -> cut over time
-- InterestCalculation
-- 3) BKN_DX_BLCK -> block account list
-- CashInterestCalculate /RetailInterestCalculate
-- 4) BKN_DX_TRXN_REC
-- 5) bkn_dx_int
-- 6) BKN_DR_TRXN_CODE
-- 7) bkn_dx_file_det

-- 8) bkn_dx_over_lmt_acct
-- 9) bkn_dl_acct
-- 10) bkn_dm_acct
-- 11) bkn_dm_acct_bal 

-- [CRD]
-- 12) CRD_DR_DATE
-- card interest calculation
-- 13) CRD_DM_CRD 
-- 14) CRD_DM_CRD_BIN 
-- 15) CRD_DM_CRD_FEE_PROF_MAP
-- 16) CRD_DM_CRD_PROD_TYP 
-- 17) CRD_DR_FEE
-- 18) CRD_DR_FEE_TYP


--BKN (late payment)
-- 19) BKN_DS_PARM 
-- 20) CMN_DR_CTRY --> swt
-- 21) BKN_DX_TRXN_TEMP
-- 22) SWT_DR_BASE_TRXN_TYP


-- 25) sequence ()
--		BKN_DQ_SERVICE_RUN
--		BKN_DQ_OVER_LMT_ACCT
--		BKN_DQ_INT
--		BKN_DQ_FILE_DET
		
-- 26) Function
--		MASK_DATA - > write java function || select IBL_D_SIM.MASK_DATA('eeed') from dual
		CREATE ALIAS MASK_DATA FOR "com.interblocks.eod.controller.Functions.MASK_DATA";
		CREATE ALIAS GET_DATA FOR "com.interblocks.eod.controller.Functions.GET_DATA";
		commit;

-- 1) 
  CREATE TABLE BKN_DX_SERVICE_RUN (	
    "SERVICE_RUN_SEQ" NUMBER(20,0), 
	"SERVICE_START_TIME" DATE, 
	"SERVICE_FINISH_TIME" DATE, 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODULE_ID" VARCHAR2(10 BYTE), 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"MESSAGE" VARCHAR2(500 CHAR), 
	"STAGE_ID" NUMBER(5,0), 
	"STAGE_DESC" VARCHAR2(100 BYTE), 
	"PRECENTAGE" NUMBER(10,0), 
	"TOT_ITEM" NUMBER(10,0), 
	"CURRENT_ITEM" NUMBER(10,0)
   );
Insert into BKN_DX_SERVICE_RUN (SERVICE_RUN_SEQ,SERVICE_START_TIME,SERVICE_FINISH_TIME,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,MODULE_ID,BANK_CODE,MESSAGE,STAGE_ID,STAGE_DESC,PRECENTAGE,TOT_ITEM,CURRENT_ITEM) values (2,SYSDATE,SYSDATE,1,'EOD_SERVICE',SYSDATE,'EOD_SERVICE',SYSDATE,'TRX_EXTRCT','0001','13:42:59 - COMPLETED SUCCESSFULLY',0,null,null,null,null);   
Insert into BKN_DX_SERVICE_RUN (SERVICE_RUN_SEQ,SERVICE_START_TIME,SERVICE_FINISH_TIME,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,MODULE_ID,BANK_CODE,MESSAGE,STAGE_ID,STAGE_DESC,PRECENTAGE,TOT_ITEM,CURRENT_ITEM) values (1,to_date('04-APR-19','DD-MON-RR'),to_date('04-APR-19','DD-MON-RR'),1,'EOD_SERVICE',to_date('04-APR-19','DD-MON-RR'),'EOD_SERVICE',to_date('04-APR-19','DD-MON-RR'),'ACS','0001','12:35:25 - COMPLETED SUCCESSFULLY',0,null,null,null,null);
Insert into BKN_DX_SERVICE_RUN (SERVICE_RUN_SEQ,SERVICE_START_TIME,SERVICE_FINISH_TIME,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,MODULE_ID,BANK_CODE,MESSAGE,STAGE_ID,STAGE_DESC,PRECENTAGE,TOT_ITEM,CURRENT_ITEM) values (2,to_date('05-APR-19','DD-MON-RR'),to_date('05-APR-19','DD-MON-RR'),1,'EOD_SERVICE',to_date('05-APR-19','DD-MON-RR'),'EOD_SERVICE',to_date('05-APR-19','DD-MON-RR'),'ACS','0001','13:42:59 - COMPLETED SUCCESSFULLY',0,null,null,null,null);
commit;

-- 2) 

CREATE TABLE BKN_DS_EOD_PARM (	
	"DATE_NO" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(12 BYTE), 
	"EOD_CUT_OFF_TIME" VARCHAR2(5 BYTE), 
	"EOD_RUN_TIME" NUMBER(4,2), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BANK_CODE" VARCHAR2(10 BYTE)
   );
   
Insert into BKN_DS_EOD_PARM (DATE_NO,DESCRIPTION,EOD_CUT_OFF_TIME,EOD_RUN_TIME,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE) values (1,'Sunday','23:00',23.05,1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'0001');
Insert into BKN_DS_EOD_PARM (DATE_NO,DESCRIPTION,EOD_CUT_OFF_TIME,EOD_RUN_TIME,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE) values (2,'Monday','23:00',23.05,1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'0001');
commit;

-- 3) 

CREATE TABLE BKN_DX_BLCK (	
  	"ATTR_TYP" VARCHAR2(20 BYTE), 
	"ATTR_ID" VARCHAR2(30 BYTE), 
	"BLCK_TYP" VARCHAR2(20 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BLCK_REF_VAL" VARCHAR2(30 BYTE)
   );
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','0000035011440000063215','INTEREST',1,'KALISI',to_date('06-APR-18','DD-MON-RR'),'KALISI',to_date('06-APR-18','DD-MON-RR'),'0');
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','0000035011440000063215','LATE_PAYMENT',1,'KALISI',to_date('06-APR-18','DD-MON-RR'),'KALISI',to_date('06-APR-18','DD-MON-RR'),'0');
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','0000035011440000063215','STMT',1,'KALISI',to_date('06-APR-18','DD-MON-RR'),'KALISI',to_date('06-APR-18','DD-MON-RR'),'0');
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','0000035011440000063215','STMT_PRNT',1,'KALISI',to_date('06-APR-18','DD-MON-RR'),'KALISI',to_date('06-APR-18','DD-MON-RR'),null);
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','0000035011440000063215','STMT_PRNT_ZERO_TRXN',1,'KALISI',to_date('06-APR-18','DD-MON-RR'),'KALISI',to_date('06-APR-18','DD-MON-RR'),'0');
Insert into BKN_DX_BLCK (ATTR_TYP,ATTR_ID,BLCK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BLCK_REF_VAL) values ('ACCT','10043011440000008931','INTEREST',1,'SHAHANI_3267',to_date('30-AUG-18','DD-MON-RR'),'SHAHANI_3267',to_date('30-AUG-18','DD-MON-RR'),null);

commit;
-- 4) BKN_DX_TRXN_REC  (txn post)
   
-- 5) 

CREATE TABLE BKN_DX_INT (	
	"INT_NO" NUMBER(20,0), 
	"ACCOUNT_SERIAL_NUMBER" NUMBER(20,0), 
	"INT_AMT" NUMBER(16,0), 
	"TRXN_TYP" VARCHAR2(3 BYTE), 
	"ORGN_TRXN_NO" NUMBER(20,0), 
	"POST_TRXN_NO" NUMBER(20,0), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"SETL_AMT" NUMBER(16,0), 
	"BANK_CODE" VARCHAR2(10 BYTE)
   );
Insert into BKN_DX_INT (INT_NO,ACCOUNT_SERIAL_NUMBER,INT_AMT,TRXN_TYP,ORGN_TRXN_NO,POST_TRXN_NO,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,SETL_AMT,BANK_CODE) values (6911,5795,100,'174',480470,0,3,'EOD_SERVICE',to_date('14-MAY-18','DD-MON-RR'),'EOD_SERVICE',to_date('17-SEP-18','DD-MON-RR'),200,'0001');
Insert into BKN_DX_INT (INT_NO,ACCOUNT_SERIAL_NUMBER,INT_AMT,TRXN_TYP,ORGN_TRXN_NO,POST_TRXN_NO,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,SETL_AMT,BANK_CODE) values (6912,6131,167,'174',480562,0,2,'EOD_SERVICE',to_date('14-MAY-18','DD-MON-RR'),'EOD_SERVICE',to_date('14-MAY-18','DD-MON-RR'),100000,'0001');
commit;

--6) 

CREATE TABLE BKN_DR_TRXN_CODE (	
	"ACCT_TYP" VARCHAR2(10 BYTE), 
	"ON_US_FLAG" VARCHAR2(20 BYTE), 
	"TRXN_TYP" VARCHAR2(3 BYTE), 
	"TRXN_CODE" VARCHAR2(3 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ACCEPTER_ID" VARCHAR2(10 BYTE)
   );
Insert into BKN_DR_TRXN_CODE (ACCT_TYP,ON_US_FLAG,TRXN_TYP,TRXN_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ACCEPTER_ID) values ('CREDIT','ALL','173','14',1,'IB',to_date('15-AUG-14','DD-MON-RR'),'IB',to_date('15-AUG-14','DD-MON-RR'),'ALL');
Insert into BKN_DR_TRXN_CODE (ACCT_TYP,ON_US_FLAG,TRXN_TYP,TRXN_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ACCEPTER_ID) values ('CREDIT','ON_US','111','14',1,'IB',to_date('15-AUG-14','DD-MON-RR'),'IB',to_date('15-AUG-14','DD-MON-RR'),'ALL');
commit;

-- 7) 

  CREATE TABLE BKN_DX_FILE_DET (	
  	"SEQ_NO" NUMBER(20,0), 
	"FILE_TYP" VARCHAR2(20 BYTE), 
	"NETWORK_ID" VARCHAR2(10 BYTE), 
	"TRANSACTION_NUMBER" VARCHAR2(14 BYTE), 
	"TRACE_NO" VARCHAR2(6 BYTE), 
	"RETRIEVAL_REF_NO" VARCHAR2(12 BYTE), 
	"TRXN_TYPE" VARCHAR2(10 BYTE), 
	"FROM_ACCOUNT_NUMBER" VARCHAR2(20 BYTE), 
	"FROM_ACCOUNT_LABEL" VARCHAR2(2 BYTE), 
	"TO_ACCOUNT_NUMBER" VARCHAR2(20 BYTE), 
	"TO_ACCOUNT_LABEL" VARCHAR2(2 BYTE), 
	"AUTHORIZATION_CODE" VARCHAR2(6 BYTE), 
	"ONUS_FLAG" VARCHAR2(1 BYTE), 
	"TRANSMISSION_DATE_TIME" VARCHAR2(14 BYTE), 
	"ACQUIRER_INSTITUTE_ID" VARCHAR2(11 BYTE), 
	"FORWARDING_INSTITUTE_ID" VARCHAR2(11 BYTE), 
	"RESPONSE_CODE" VARCHAR2(3 BYTE), 
	"MERCHANT_CATEGORY" VARCHAR2(4 BYTE), 
	"ADD_DATE" VARCHAR2(14 BYTE), 
	"ACCEPTOR_TERMINAL_ID" VARCHAR2(8 BYTE), 
	"TRXN_PRODUCT_TYPE" VARCHAR2(5 BYTE), 
	"CARD_NUMBER" VARCHAR2(70 BYTE), 
	"CUSTOMER_NUMBER" VARCHAR2(12 BYTE), 
	"CARD_BRANCH_CODE" VARCHAR2(4 BYTE), 
	"TRXN_BRANCH_CODE" VARCHAR2(4 BYTE), 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"ACCEPTOR_NAME_LOCATION" VARCHAR2(40 BYTE), 
	"TRX_AMOUNT" VARCHAR2(16 BYTE), 
	"TRX_CURRENCY_ID" VARCHAR2(3 BYTE), 
	"BILL_AMOUNT" VARCHAR2(16 BYTE), 
	"BILL_CURRENCY_ID" VARCHAR2(3 BYTE), 
	"STATUS_CODE" VARCHAR2(3 BYTE), 
	"BATCH_ID" VARCHAR2(20 BYTE), 
	"ORI_TRX_NO" VARCHAR2(20 BYTE), 
	"STATUS" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ORI_TRANSACTION_TYPE" VARCHAR2(10 BYTE), 
	"ORI_TERM_ID" VARCHAR2(10 BYTE), 
	"ORI_ACCT_NO" VARCHAR2(30 BYTE), 
	"REASON" VARCHAR2(100 BYTE), 
	"TOTAL_FEE" VARCHAR2(12 BYTE), 
	"ISUR_FEE" VARCHAR2(12 BYTE), 
	"BENF_FEE" VARCHAR2(12 BYTE), 
	"NTWK_FEE" VARCHAR2(12 BYTE), 
	"TRX_TYPE_FLAG" VARCHAR2(10 BYTE)
   );
   
Insert into BKN_DX_FILE_DET (SEQ_NO,FILE_TYP,NETWORK_ID,TRANSACTION_NUMBER,TRACE_NO,RETRIEVAL_REF_NO,TRXN_TYPE,FROM_ACCOUNT_NUMBER,FROM_ACCOUNT_LABEL,TO_ACCOUNT_NUMBER,TO_ACCOUNT_LABEL,AUTHORIZATION_CODE,ONUS_FLAG,TRANSMISSION_DATE_TIME,ACQUIRER_INSTITUTE_ID,FORWARDING_INSTITUTE_ID,RESPONSE_CODE,MERCHANT_CATEGORY,ADD_DATE,ACCEPTOR_TERMINAL_ID,TRXN_PRODUCT_TYPE,CARD_NUMBER,CUSTOMER_NUMBER,CARD_BRANCH_CODE,TRXN_BRANCH_CODE,BANK_CODE,ACCEPTOR_NAME_LOCATION,TRX_AMOUNT,TRX_CURRENCY_ID,BILL_AMOUNT,BILL_CURRENCY_ID,STATUS_CODE,BATCH_ID,ORI_TRX_NO,STATUS,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ORI_TRANSACTION_TYPE,ORI_TERM_ID,ORI_ACCT_NO,REASON,TOTAL_FEE,ISUR_FEE,BENF_FEE,NTWK_FEE,TRX_TYPE_FLAG) values (40233,'CREDIT','          ','              ','575194','012916575194','          ','                    ','NA','                    ','NA','314144','Y','20180129163835','          0','          0',' 00','0000','20180215234014','CMS00001','     ','                    ','            ',' 010','    ','        ','Credit Card Payment---Vattanac Bank---KH','0000000000000000','000','0000000009000000','144','001',null,'479665',3,'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),null,null,null,null,null,null,null,null,null);
Insert into BKN_DX_FILE_DET (SEQ_NO,FILE_TYP,NETWORK_ID,TRANSACTION_NUMBER,TRACE_NO,RETRIEVAL_REF_NO,TRXN_TYPE,FROM_ACCOUNT_NUMBER,FROM_ACCOUNT_LABEL,TO_ACCOUNT_NUMBER,TO_ACCOUNT_LABEL,AUTHORIZATION_CODE,ONUS_FLAG,TRANSMISSION_DATE_TIME,ACQUIRER_INSTITUTE_ID,FORWARDING_INSTITUTE_ID,RESPONSE_CODE,MERCHANT_CATEGORY,ADD_DATE,ACCEPTOR_TERMINAL_ID,TRXN_PRODUCT_TYPE,CARD_NUMBER,CUSTOMER_NUMBER,CARD_BRANCH_CODE,TRXN_BRANCH_CODE,BANK_CODE,ACCEPTOR_NAME_LOCATION,TRX_AMOUNT,TRX_CURRENCY_ID,BILL_AMOUNT,BILL_CURRENCY_ID,STATUS_CODE,BATCH_ID,ORI_TRX_NO,STATUS,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ORI_TRANSACTION_TYPE,ORI_TERM_ID,ORI_ACCT_NO,REASON,TOTAL_FEE,ISUR_FEE,BENF_FEE,NTWK_FEE,TRX_TYPE_FLAG) values (40234,'CREDIT','          ','              ','575344','013008575344','          ','                    ','NA','                    ','NA','058668','Y','20180130083748','          0','          0',' 00','0000','20180215234014','CMS00001','     ','                    ','            ',' 010','    ','        ','Credit Card Payment---Vattanac Bank---KH','0000000000000000','000','0000000009000000','144','001',null,'479690',3,'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),null,null,null,null,null,null,null,null,null);
Insert into BKN_DX_FILE_DET (SEQ_NO,FILE_TYP,NETWORK_ID,TRANSACTION_NUMBER,TRACE_NO,RETRIEVAL_REF_NO,TRXN_TYPE,FROM_ACCOUNT_NUMBER,FROM_ACCOUNT_LABEL,TO_ACCOUNT_NUMBER,TO_ACCOUNT_LABEL,AUTHORIZATION_CODE,ONUS_FLAG,TRANSMISSION_DATE_TIME,ACQUIRER_INSTITUTE_ID,FORWARDING_INSTITUTE_ID,RESPONSE_CODE,MERCHANT_CATEGORY,ADD_DATE,ACCEPTOR_TERMINAL_ID,TRXN_PRODUCT_TYPE,CARD_NUMBER,CUSTOMER_NUMBER,CARD_BRANCH_CODE,TRXN_BRANCH_CODE,BANK_CODE,ACCEPTOR_NAME_LOCATION,TRX_AMOUNT,TRX_CURRENCY_ID,BILL_AMOUNT,BILL_CURRENCY_ID,STATUS_CODE,BATCH_ID,ORI_TRX_NO,STATUS,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ORI_TRANSACTION_TYPE,ORI_TERM_ID,ORI_ACCT_NO,REASON,TOTAL_FEE,ISUR_FEE,BENF_FEE,NTWK_FEE,TRX_TYPE_FLAG) values (40235,'CREDIT','          ','              ','574676','802512574676','        17','                    ','NA','                    ','NA','522326','Y','20180102162741','     888888','          0',' 00','0000','20180215234014','CMS00001','     ','                    ','            ',' 010','    ','        ','Vattanac Bank          PhnomPenh      KH','0000000000000000','000','0000000000050000','144','001',null,'479609',5,'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),'EOD_SERVICE',to_date('15-FEB-18','DD-MON-RR'),null,null,null,null,null,null,null,null,null);
commit;

-- 8)
  CREATE TABLE BKN_DX_OVER_LMT_ACCT (	
  	"SEQ_NO" VARCHAR2(20 BYTE), 
	"ACCOUNT_SERIAL_NUMBER" NUMBER(20,0), 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE), 
	"CARD_LIMIT" NUMBER(20,0), 
	"EXCEED_AMNT" NUMBER(20,0), 
	"ADDED_DATE" DATE, 
	"ADDED_BY" VARCHAR2(40 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"MODIFIED_BY" VARCHAR2(40 BYTE), 
	"MODIFIED_DATE" DATE
   );
   	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('12',2,'0000035011440000062001',12,2,to_date('09-APR-10','DD-MON-RR'),' ad ',2,'quis nostrud exercitation ul',to_date('20-APR-54','DD-MON-RR'));
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('o laboris nisi ut al',3,'0000037011440000067980',2,3,to_date('19-JUN-18','DD-MON-RR'),'se c',3,'or sit amet, consectetur adipi',to_date('25-FEB-29','DD-MON-RR'));
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('re magna aliqu',4,'sed do eiu',3,4,to_date('23-MAR-39','DD-MON-RR'),'a aliqua. Ut en',4,'itation ullamco laboris nis',to_date('02-MAR-92','DD-MON-RR'));
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('ud exer',0,'ui officia d',0,0,to_date('18-APR-52','DD-MON-RR'),'lamc',0,'aute irure ',to_date('08-SEP-23','DD-MON-RR'));
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('idunt ut la',1,'in culpa',null,1,to_date('29-APR-78','DD-MON-RR'),'nim id est laborum.Lorem ip',1,'mmodo consequat. Duis aute irur',to_date('14-OCT-54','DD-MON-RR'));
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('124',5642,'0000035011440000057050',null,41839348,to_date('26-NOV-18','DD-MON-RR'),'EOD_SERVER',1,null,null);
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('125',5681,'0000035011440000057480',null,1967333058,to_date('26-NOV-18','DD-MON-RR'),'EOD_SERVER',1,null,null);
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('126',5593,'0000032011440000056562',null,69971893033,to_date('26-NOV-18','DD-MON-RR'),'EOD_SERVER',1,null,null);
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('127',6252,'0000035011440000063215',null,995600,to_date('26-NOV-18','DD-MON-RR'),'EOD_SERVER',1,null,null);
	Insert into BKN_DX_OVER_LMT_ACCT (SEQ_NO,ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,CARD_LIMIT,EXCEED_AMNT,ADDED_DATE,ADDED_BY,STATUS_CODE,MODIFIED_BY,MODIFIED_DATE) values ('128',6868,'0000039011440000069628',null,1023400,to_date('26-NOV-18','DD-MON-RR'),'EOD_SERVER',1,null,null);
   
-- 9)
CREATE TABLE BKN_DL_ACCT(	
	"FROM_ACCT_SERIAL_NO" NUMBER(20,0), 
	"TO_ACCT_SERIAL_NO" NUMBER(20,0), 
	"LINK_TYP" VARCHAR2(20 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE
   );
   
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5621,5622,'SPLMNTR',1,'CBE',to_date('25-JAN-18','DD-MON-RR'),'CBE',to_date('25-JAN-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5609,5650,'SPLMNTR',1,'CBE',to_date('05-FEB-18','DD-MON-RR'),'CBE',to_date('05-FEB-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5965,5979,'SPLMNTR',1,'CBE',to_date('07-MAR-18','DD-MON-RR'),'CBE',to_date('07-MAR-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5965,5980,'SPLMNTR',1,'CBE',to_date('07-MAR-18','DD-MON-RR'),'CBE',to_date('07-MAR-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5981,5983,'COMP',1,'CBE',to_date('08-MAR-18','DD-MON-RR'),'CBE',to_date('08-MAR-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5983,5984,'DEPT',1,'CBE',to_date('08-MAR-18','DD-MON-RR'),'CBE',to_date('08-MAR-18','DD-MON-RR'));
Insert into BKN_DL_ACCT (FROM_ACCT_SERIAL_NO,TO_ACCT_SERIAL_NO,LINK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5983,5985,'DEPT',1,'CBE',to_date('08-MAR-18','DD-MON-RR'),'CBE',to_date('08-MAR-18','DD-MON-RR'));

-- 10) 
  CREATE TABLE BKN_DM_ACCT (	
	"ACCOUNT_SERIAL_NUMBER" NUMBER(20,0), 
	"ACCOUNT_NUMBER" VARCHAR2(30 BYTE), 
	"NODE_ID" VARCHAR2(10 BYTE), 
	"CURRENCY_CODE" VARCHAR2(3 BYTE), 
	"ACCOUNT_TYPE" VARCHAR2(10 BYTE), 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"BRANCH_CODE" VARCHAR2(10 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"ISSUE_TYP" VARCHAR2(10 BYTE)
   );
   
   Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5595,'0000032061440000056587',null,'144','SVC','0001','00000',1,'CBE',to_date('19-JAN-18','DD-MON-RR'),'CBE',to_date('19-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5609,'0000035011440000056722',null,'144','SVC','0001','00000',1,'CBE',to_date('24-JAN-18','DD-MON-RR'),'CBE',to_date('24-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5610,'00068011440000212094',null,'144','CREDIT','0001','00000',1,'CBE',to_date('24-JAN-18','DD-MON-RR'),'CBE',to_date('24-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5619,'0000035041440000056825','1','144','CMSN','0001','00000',1,'JAYRIDA',to_date('25-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('25-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5615,'0000035011440000056789',null,'144','CREDIT','0001','00000',1,'CBE',to_date('25-JAN-18','DD-MON-RR'),'CBE',to_date('25-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5617,'0000035011440000056805',null,'144','CREDIT','0001','00000',1,'CBE',to_date('25-JAN-18','DD-MON-RR'),'CBE',to_date('25-JAN-18','DD-MON-RR'),'INDVDL');
Insert into BKN_DM_ACCT (ACCOUNT_SERIAL_NUMBER,ACCOUNT_NUMBER,NODE_ID,CURRENCY_CODE,ACCOUNT_TYPE,BANK_CODE,BRANCH_CODE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,ISSUE_TYP) values (5618,'0000035031440000056819','1','144','MERC','0001','00000',4,'JAYRIDA',to_date('25-JAN-18','DD-MON-RR'),'JALIYA',to_date('17-JUL-18','DD-MON-RR'),'INDVDL');
   
-- 11)
CREATE TABLE BKN_DM_ACCT_BAL(	
	"ACCOUNT_SERIAL_NUMBER" NUMBER(20,0), 
	"BALANCE_TYPE" VARCHAR2(10 BYTE), 
	"BROUGHT_FORWARD" NUMBER(20,0), 
	"CURRENT_OUTSTANDING" NUMBER(20,0), 
	"TOTAL_OUTSTANDING" NUMBER(20,0), 
	"NOT_SETTLE" NUMBER(20,0), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE
   );
   
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5625,'BNK_CHRG',0,0,0,0,1,'CBE',to_date('26-JAN-18','DD-MON-RR'),'CBE',to_date('26-JAN-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'BNK_CHRG',0,0,0,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('11-DEC-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'CARD_LIMIT',0,0,10000000,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'CBE',to_date('18-JAN-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'CASH_LIMIT',0,0,5000000,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'CBE',to_date('18-JAN-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'CSH_ADVNC',0,0,0,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('11-DEC-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'IIS',0,0,0,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('11-DEC-18','DD-MON-RR'));
Insert into BKN_DM_ACCT_BAL (ACCOUNT_SERIAL_NUMBER,BALANCE_TYPE,BROUGHT_FORWARD,CURRENT_OUTSTANDING,TOTAL_OUTSTANDING,NOT_SETTLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values (5590,'PAYMENT',0,0,0,0,1,'CBE',to_date('18-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('11-DEC-18','DD-MON-RR'));
   
-- 12)
  CREATE TABLE CRD_DR_DATE (	
	"REF_GRP" VARCHAR2(20 BYTE), 
	"REF_TYP" VARCHAR2(20 BYTE), 
	"REF_VAL" VARCHAR2(70 BYTE), 
	"NEXT_DATE" DATE, 
	"EXP_DATE" DATE, 
	"INC_TYP" VARCHAR2(20 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(20 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"LNK_NO" VARCHAR2(10 BYTE)
   );
   
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('STMT_DATE','ACCOUNT','0000032011440000056562',to_date('27-SEP-18','DD-MON-RR'),null,'MONTHLY',1,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('28-AUG-18','DD-MON-RR'),'0001','940632');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('DUE_DATE','ACCOUNT','0000032011440000056562',to_date('11-SEP-18','DD-MON-RR'),null,'MONTHLY',1,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'EOM_SERVICE',to_date('28-AUG-18','DD-MON-RR'),'0001','940632');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('AUTO_PAY_DATE','ACCOUNT','0000032011440000056562',to_date('08-SEP-18','DD-MON-RR'),null,'MONTHLY',2,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'EOD_SERVICE',to_date('17-SEP-18','DD-MON-RR'),'0001','940632');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('GRC_PRD_DATE','ACCOUNT','0000032011440000056562',to_date('11-SEP-18','DD-MON-RR'),null,'MONTHLY',2,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'EOD_SERVICE',to_date('17-SEP-18','DD-MON-RR'),'0001','940632');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('ANNUAL_FEE','CARD','001A915F7DD5CE003C13072989EE587CA26FA67F3A2FD420C8618B7C343E2071889',null,null,'ANNUAL',1,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'0001','940641');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('ANNUAL_FEE','CARD','001078E1D9EDD176EAF53391621184B1528B79614FAB42749123B9B09E9FE6CE656',null,null,'ANNUAL',1,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'PASINDU',to_date('04-SEP-18','DD-MON-RR'),'0001','1006374');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('RENEW_FEE','CARD','001078E1D9EDD176EAF53391621184B1528B79614FAB42749123B9B09E9FE6CE656',null,null,'ANNUAL',1,'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'PASINDU',to_date('04-SEP-18','DD-MON-RR'),'0001','1006374');
Insert into CRD_DR_DATE (REF_GRP,REF_TYP,REF_VAL,NEXT_DATE,EXP_DATE,INC_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO) values ('ANNUAL_FEE','CARD','001A8B30AB525792E5B31B442A94607CEAD01EF4BC3384CB0A3E363AABCCDA20991',null,null,'ANNUAL',1,'JAYRIDA',to_date('29-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('29-JAN-18','DD-MON-RR'),'0001','949658');


-- 13) CRD_DM_CRD 
  CREATE TABLE CRD_DM_CRD(
  	"CARD_NO" VARCHAR2(70 BYTE), 
	"CUST_SERIAL_NO" VARCHAR2(20 BYTE), 
	"CUST_MENU_OPT" VARCHAR2(25 BYTE) DEFAULT 0, 
	"CORE_BANKING_REFNO" VARCHAR2(20 BYTE), 
	"NAME_ON_CARD" VARCHAR2(50 BYTE), 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"BRANCH_CODE" VARCHAR2(10 BYTE), 
	"COLLECTION_BRANCH" VARCHAR2(10 BYTE), 
	"EXPIRY_DATE" DATE, 
	"PRIMARY_ACC_NUM" VARCHAR2(24 BYTE), 
	"CARD_TYP" VARCHAR2(10 BYTE), 
	"PRODUCT_TYP" VARCHAR2(15 BYTE), 
	"NETWORK_TYP" VARCHAR2(10 BYTE), 
	"CATEGORY_ID" VARCHAR2(10 BYTE), 
	"COMPANY_ID" VARCHAR2(20 BYTE), 
	"CARD_PROFILE" VARCHAR2(20 BYTE), 
	"TERMINAL_PROFILE" VARCHAR2(20 BYTE), 
	"FACE_TYP" VARCHAR2(20 BYTE), 
	"ISSUE_TYP" VARCHAR2(20 BYTE), 
	"PVK" VARCHAR2(32 BYTE), 
	"CVK1" VARCHAR2(32 BYTE), 
	"CVK2" VARCHAR2(32 BYTE), 
	"REF_NO" VARCHAR2(20 BYTE), 
	"PIN_OFFSET" VARCHAR2(12 BYTE), 
	"SEC_CODE" VARCHAR2(20 BYTE), 
	"LANGUAGE" VARCHAR2(3 BYTE), 
	"ISSUE_NO" NUMBER(2,0) DEFAULT 1, 
	"PIN_ERROR_COUNT" VARCHAR2(1 BYTE), 
	"FILE_DOWNLOAD" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BATCH_NO" VARCHAR2(20 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"AUTH_DATE" DATE, 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"LNK_NO" VARCHAR2(10 BYTE), 
	"CORP_DEPT_ID" VARCHAR2(10 BYTE), 
	"BILL_ADDR_TYP" VARCHAR2(1 BYTE), 
	"MODIF_FILE_DOWNLOAD" VARCHAR2(1 BYTE), 
	"CRD_SEARCH" VARCHAR2(22 BYTE), 
	"ENCODE_FILE_NAME" VARCHAR2(100 BYTE), 
	"DEL_TYP" VARCHAR2(3 BYTE), 
	"EMB_NAME1" VARCHAR2(50 BYTE), 
	"EMB_NAME2" VARCHAR2(50 BYTE), 
	"CARD_SEQ" NUMBER, 
	"ALT_TYP" VARCHAR2(10 BYTE), 
	"TRX_STATUS" NUMBER(2,0), 
	"OTP_REF" VARCHAR2(20 BYTE)
   );

Insert into CRD_DM_CRD (CARD_NO,CUST_SERIAL_NO,CUST_MENU_OPT,CORE_BANKING_REFNO,NAME_ON_CARD,BANK_CODE,BRANCH_CODE,COLLECTION_BRANCH,EXPIRY_DATE,PRIMARY_ACC_NUM,CARD_TYP,PRODUCT_TYP,NETWORK_TYP,CATEGORY_ID,COMPANY_ID,CARD_PROFILE,TERMINAL_PROFILE,FACE_TYP,ISSUE_TYP,PVK,CVK1,CVK2,REF_NO,PIN_OFFSET,SEC_CODE,LANGUAGE,ISSUE_NO,PIN_ERROR_COUNT,FILE_DOWNLOAD,BATCH_NO,STATUS_CODE,AUTH_DATE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,CORP_DEPT_ID,BILL_ADDR_TYP,MODIF_FILE_DOWNLOAD,CRD_SEARCH,ENCODE_FILE_NAME,DEL_TYP,EMB_NAME1,EMB_NAME2,CARD_SEQ,ALT_TYP,TRX_STATUS,OTP_REF) values ('0016878F235DF4BBFE37E82538B200237255CE61C463AFCFACBBC4DB26237511326','9226','0','1001','JALIYA','0001','00000','00000',to_date('30-SEP-23','DD-MON-RR'),'0000035011440000062001','CREDIT','PRD562','VISA','NORM',null,'VISA_PRSNLSD_CR','PROF1004','PRSNLSD','PRNCPL','BED708EF584909AD','3499F48C1E115AB8','18A0FB35E3EF8611','000000','415151','800000N2FFFF','eng',1,'0','N',null,1,to_date('19-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'SUPUNTEST',to_date('05-DEC-18','DD-MON-RR'),'1018710',null,null,null,'0032',null,null,'TEST','TEST',1,null,1,null);
Insert into CRD_DM_CRD (CARD_NO,CUST_SERIAL_NO,CUST_MENU_OPT,CORE_BANKING_REFNO,NAME_ON_CARD,BANK_CODE,BRANCH_CODE,COLLECTION_BRANCH,EXPIRY_DATE,PRIMARY_ACC_NUM,CARD_TYP,PRODUCT_TYP,NETWORK_TYP,CATEGORY_ID,COMPANY_ID,CARD_PROFILE,TERMINAL_PROFILE,FACE_TYP,ISSUE_TYP,PVK,CVK1,CVK2,REF_NO,PIN_OFFSET,SEC_CODE,LANGUAGE,ISSUE_NO,PIN_ERROR_COUNT,FILE_DOWNLOAD,BATCH_NO,STATUS_CODE,AUTH_DATE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,CORP_DEPT_ID,BILL_ADDR_TYP,MODIF_FILE_DOWNLOAD,CRD_SEARCH,ENCODE_FILE_NAME,DEL_TYP,EMB_NAME1,EMB_NAME2,CARD_SEQ,ALT_TYP,TRX_STATUS,OTP_REF) values ('001078E1D9EDD176EAF53391621184B1528B79614FAB42749123B9B09E9FE6CE656','9226','0','1001','SVC JALIYA','0001','00000','00000',to_date('31-JAN-21','DD-MON-RR'),'0000032061440000056579','SVC','PRD563','VISA','NORM',null,'VISA_PRSNLSD_SV','PROF676','PRSNLSD','PRNCPL','BA02E2B320E89465','F9F892F8DEEDD129','4B9A1E1673C3F01E','000000','034431','400000N8FFFF','eng',1,'0','N',null,1,to_date('04-SEP-18','DD-MON-RR'),'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'PASINDU',to_date('04-SEP-18','DD-MON-RR'),'1006374',null,null,null,'0018',null,null,'TEST','TEST',2,null,null,null);
Insert into CRD_DM_CRD (CARD_NO,CUST_SERIAL_NO,CUST_MENU_OPT,CORE_BANKING_REFNO,NAME_ON_CARD,BANK_CODE,BRANCH_CODE,COLLECTION_BRANCH,EXPIRY_DATE,PRIMARY_ACC_NUM,CARD_TYP,PRODUCT_TYP,NETWORK_TYP,CATEGORY_ID,COMPANY_ID,CARD_PROFILE,TERMINAL_PROFILE,FACE_TYP,ISSUE_TYP,PVK,CVK1,CVK2,REF_NO,PIN_OFFSET,SEC_CODE,LANGUAGE,ISSUE_NO,PIN_ERROR_COUNT,FILE_DOWNLOAD,BATCH_NO,STATUS_CODE,AUTH_DATE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,CORP_DEPT_ID,BILL_ADDR_TYP,MODIF_FILE_DOWNLOAD,CRD_SEARCH,ENCODE_FILE_NAME,DEL_TYP,EMB_NAME1,EMB_NAME2,CARD_SEQ,ALT_TYP,TRX_STATUS,OTP_REF) values ('001CF99EC91DC709E68DDFBB12B5E4C3B0A00C13D4CF4F973F55DDA949FEF77D45A','9226','0','1001','SVC CARD','0001','00000','00000',to_date('31-JAN-21','DD-MON-RR'),'0000032061440000056587','SVC','PRD563','VISA','NORM',null,'VISA_PRSNLSD_SV','PROF676','PRSNLSD','PRNCPL','BA02E2B320E89465','F9F892F8DEEDD129','4B9A1E1673C3F01E','000000','578564','400000N6FFFF','eng',1,'0','N',null,95,to_date('19-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('19-JAN-18','DD-MON-RR'),'JAYRIDA',to_date('29-JAN-18','DD-MON-RR'),'949658',null,null,null,'0026',null,null,'TEST','TEST',3,null,null,null);
Insert into CRD_DM_CRD (CARD_NO,CUST_SERIAL_NO,CUST_MENU_OPT,CORE_BANKING_REFNO,NAME_ON_CARD,BANK_CODE,BRANCH_CODE,COLLECTION_BRANCH,EXPIRY_DATE,PRIMARY_ACC_NUM,CARD_TYP,PRODUCT_TYP,NETWORK_TYP,CATEGORY_ID,COMPANY_ID,CARD_PROFILE,TERMINAL_PROFILE,FACE_TYP,ISSUE_TYP,PVK,CVK1,CVK2,REF_NO,PIN_OFFSET,SEC_CODE,LANGUAGE,ISSUE_NO,PIN_ERROR_COUNT,FILE_DOWNLOAD,BATCH_NO,STATUS_CODE,AUTH_DATE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,CORP_DEPT_ID,BILL_ADDR_TYP,MODIF_FILE_DOWNLOAD,CRD_SEARCH,ENCODE_FILE_NAME,DEL_TYP,EMB_NAME1,EMB_NAME2,CARD_SEQ,ALT_TYP,TRX_STATUS,OTP_REF) values ('0010841B2C1BA83BA6E537A89F779BF600ACE37B97E70D2098F10FA78F8AFE2F96F','9628','0','111111','LASITHA CARD','0001','1234','00000',to_date('14-AUG-18','DD-MON-RR'),'240000000001','DEBIT','PRD615','VISA','NORM',null,'VISA_PRSNLSD_DR','PROF776','PRSNLSD','PRNCPL','6BFA0B884EA61F8A','95B3B151F6EFE94E','1876B29D2F33DB21','000000','9253','400002N7FFFF','ENG',1,'5','N',null,97,to_date('12-FEB-18','DD-MON-RR'),'LASITHA',to_date('12-FEB-18','DD-MON-RR'),'JALIYA',to_date('02-JUL-18','DD-MON-RR'),'989208',null,null,null,'0060',null,null,'TEST','TEST',4,null,null,null);
Insert into CRD_DM_CRD (CARD_NO,CUST_SERIAL_NO,CUST_MENU_OPT,CORE_BANKING_REFNO,NAME_ON_CARD,BANK_CODE,BRANCH_CODE,COLLECTION_BRANCH,EXPIRY_DATE,PRIMARY_ACC_NUM,CARD_TYP,PRODUCT_TYP,NETWORK_TYP,CATEGORY_ID,COMPANY_ID,CARD_PROFILE,TERMINAL_PROFILE,FACE_TYP,ISSUE_TYP,PVK,CVK1,CVK2,REF_NO,PIN_OFFSET,SEC_CODE,LANGUAGE,ISSUE_NO,PIN_ERROR_COUNT,FILE_DOWNLOAD,BATCH_NO,STATUS_CODE,AUTH_DATE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,CORP_DEPT_ID,BILL_ADDR_TYP,MODIF_FILE_DOWNLOAD,CRD_SEARCH,ENCODE_FILE_NAME,DEL_TYP,EMB_NAME1,EMB_NAME2,CARD_SEQ,ALT_TYP,TRX_STATUS,OTP_REF) values ('0011FCF1C8F41F1F9277E1AECECC963D741824EE2CF80EEE27014D9E8B4D3EEA60A','10589','0','10589',' ','0001','00000','00000',to_date('31-MAR-21','DD-MON-RR'),'0000035061440000059394','SVC','PRD666','VISA','NORM',null,'VISA_NPRSNLSD_SV','PROF676','NPRSNLSD','PRNCPL','BED708EF584909AD','3499F48C1E115AB8','18A0FB35E3EF8611','000000','0464','400006N9FFFF','eng',1,'0','N','39522',1,null,'AMILATEST',to_date('02-MAR-18','DD-MON-RR'),'INFUSER',to_date('09-MAY-18','DD-MON-RR'),'0',null,null,null,null,null,null,'TEST','TEST',5,null,null,null);



-- 14) CRD_DM_CRD_BIN 
  CREATE TABLE CRD_DM_CRD_BIN(
  	"BIN_NO" VARCHAR2(10 BYTE), 
	"CARD_TYP" VARCHAR2(10 BYTE), 
	"NETWORK_TYP" VARCHAR2(10 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"DEF_CURR_CODE" VARCHAR2(10 BYTE)
   );

Insert into CRD_DM_CRD_BIN (BIN_NO,CARD_TYP,NETWORK_TYP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,DEF_CURR_CODE) values ('469169','DEBIT','PROPNTWK',1,'IB',to_date('26-OCT-11','DD-MON-RR'),'IB',to_date('26-OCT-11','DD-MON-RR'),'0001','144');


-- 15) CRD_DM_CRD_FEE_PROF_MAP
  CREATE TABLE CRD_DM_CRD_FEE_PROF_MAP(
  	"CARD_NO" VARCHAR2(100 BYTE), 
	"PROFILE_NAME" VARCHAR2(50 BYTE), 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" DATE
   );
   
Insert into CRD_DM_CRD_FEE_PROF_MAP (CARD_NO,PROFILE_NAME,MODIFIED_BY,MODIFIED_DATE) values ('0018321749B6D5380355F91084DD74C29A2F259A7FE7F912B4D63019F76DAE17F9A','PROF695','THILINA',to_date('06-APR-18','DD-MON-RR'));
Insert into CRD_DM_CRD_FEE_PROF_MAP (CARD_NO,PROFILE_NAME,MODIFIED_BY,MODIFIED_DATE) values ('0016325E698E5CEB28CC5723A64768CF6F95EA4F3966B6B8759E6FE80F012F07CDF','PROF845','VIDUNA',to_date('31-AUG-18','DD-MON-RR'));
Insert into CRD_DM_CRD_FEE_PROF_MAP (CARD_NO,PROFILE_NAME,MODIFIED_BY,MODIFIED_DATE) values ('001A147824B79736552E170EB0E9AA1ECC4F3EF153F05F048EAE35AE7DA11F4FC8C','PROF695','TECKLA',to_date('10-AUG-18','DD-MON-RR'));
   

-- 16) CRD_DM_CRD_PROD_TYP 
CREATE TABLE CRD_DM_CRD_PROD_TYP(
	"PRODUCT_TYP" VARCHAR2(20 BYTE), 
	"PRODUCT_DESC" VARCHAR2(100 BYTE), 
	"PRODUCT_CODE" VARCHAR2(3 BYTE), 
	"PRODUCT_BIN" VARCHAR2(15 BYTE), 
	"PRODUCT_SCORE" NUMBER(2,0), 
	"CARD_TYP" VARCHAR2(10 BYTE), 
	"NETWORK_TYP" VARCHAR2(10 BYTE), 
	"SERIAL_TYP" VARCHAR2(20 BYTE), 
	"ACCOUNT_PROFILE" VARCHAR2(20 BYTE), 
	"TERMINAL_PROFILE" VARCHAR2(20 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"LNK_NO" VARCHAR2(10 BYTE), 
	"PERIOD_TYP" CHAR(1 BYTE), 
	"PERIOD" NUMBER(2,0), 
	"PHYSCL_TYP" VARCHAR2(25 BYTE), 
	"EXTTRXFLAG" VARCHAR2(10 BYTE), 
	"SERVICE_CODE" VARCHAR2(3 BYTE), 
	"NAME_ON_CARD" VARCHAR2(50 BYTE), 
	"EXT_REF_NUM" VARCHAR2(20 BYTE)
   );
   
Insert into CRD_DM_CRD_PROD_TYP (PRODUCT_TYP,PRODUCT_DESC,PRODUCT_CODE,PRODUCT_BIN,PRODUCT_SCORE,CARD_TYP,NETWORK_TYP,SERIAL_TYP,ACCOUNT_PROFILE,TERMINAL_PROFILE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,LNK_NO,PERIOD_TYP,PERIOD,PHYSCL_TYP,EXTTRXFLAG,SERVICE_CODE,NAME_ON_CARD,EXT_REF_NUM) values ('PRD562','SVC PRODUCT','04','469169',0,'SVC','VISA','P',null,'PROF676',1,'RUSITHCARD',to_date('27-MAR-19','DD-MON-RR'),'RUSITHCARD',to_date('09-APR-19','DD-MON-RR'),'0001','1024426',null,0,'PLSTC',null,null,'WELCOME',null);

-- 17) CRD_DR_FEE
CREATE TABLE CRD_DR_FEE(
	"FEE_REF" VARCHAR2(70 BYTE), 
	"FEE_REF_TYP" VARCHAR2(20 BYTE), 
	"FEE_ID" VARCHAR2(50 BYTE), 
	"FEE_FROM" NUMBER(9,2) DEFAULT 0, 
	"FEE_TO" NUMBER(9,2) DEFAULT (-1), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(20 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" DATE, 
	"LNK_NO" VARCHAR2(10 BYTE), 
	"FEE_CURR_ID" VARCHAR2(3 BYTE), 
	"FEE_RULE_ID" VARCHAR2(20 BYTE), 
	"FEE" NUMBER(12,5), 
	"MIN_FEE" NUMBER(12,0), 
	"FEE_PERIOD" VARCHAR2(30 BYTE), 
	"FEE_CALC" VARCHAR2(2 BYTE)
   );
   
Insert into CRD_DR_FEE (FEE_REF,FEE_REF_TYP,FEE_ID,FEE_FROM,FEE_TO,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,LNK_NO,FEE_CURR_ID,FEE_RULE_ID,FEE,MIN_FEE,FEE_PERIOD,FEE_CALC) values ('PRD562','PRODUCT','INTEREST_FEE',0,-1,1,'AMILATEST',to_date('18-SEP-18','DD-MON-RR'),'RUSITHCARD',to_date('27-MAR-19','DD-MON-RR'),'1023825','144',null,50,0,'TRXN','FT');
   
-- 18) CRD_DR_FEE_TYP

CREATE TABLE CRD_DR_FEE_TYP(
	"FEE_ID" VARCHAR2(50 BYTE), 
	"FEE_DESC" VARCHAR2(50 BYTE), 
	"CARD_TYP" VARCHAR2(10 BYTE), 
	"NETWORK_TYP" VARCHAR2(10 BYTE), 
	"FEE_TYP" VARCHAR2(50 BYTE), 
	"FEE_CURR_ID" VARCHAR2(3 BYTE), 
	"FEE_CURR_PREC" NUMBER(10,0), 
	"FEE_ORDER" NUMBER(10,0), 
	"FEE_PERIOD" VARCHAR2(30 BYTE), 
	"FEE_FROM" NUMBER(10,0) DEFAULT 0, 
	"FEE_TO" NUMBER(10,0) DEFAULT (-1), 
	"VISIBILITY" NUMBER(10,0), 
	"SWT_TRXN_TYP" VARCHAR2(10 BYTE), 
	"FEE_CALC" VARCHAR2(2 BYTE), 
	"APPR_ON_FEE_EXP" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(20 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(20 BYTE), 
	"MODIFIED_DATE" DATE
   );
Insert into CRD_DR_FEE_TYP (FEE_ID,FEE_DESC,CARD_TYP,NETWORK_TYP,FEE_TYP,FEE_CURR_ID,FEE_CURR_PREC,FEE_ORDER,FEE_PERIOD,FEE_FROM,FEE_TO,VISIBILITY,SWT_TRXN_TYP,FEE_CALC,APPR_ON_FEE_EXP,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values ('INTEREST_FEE','Annual Fee','SVC','VISA','ANNUAL_FEE','144',100,1,'ANNUAL',0,-1,1,'80','FT','Y',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'));

-- 19) BKN_DS_PARM
  CREATE TABLE BKN_DS_PARM(
  	"CONFIG_ID" VARCHAR2(30 BYTE), 
	"CONFIG_VAL" VARCHAR2(50 BYTE), 
	"CONFIG_DES" VARCHAR2(50 BYTE), 
	"IS_VARIABLE" VARCHAR2(1 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"APP_ID" VARCHAR2(10 BYTE)
   );
   
Insert into BKN_DS_PARM (CONFIG_ID,CONFIG_VAL,CONFIG_DES,IS_VARIABLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,APP_ID) values ('SVC_ALL_TIME_MAX_ACC_BAL_LIMIT','500000','SVC ALLTime Balance Limit','N',1,'PRASADR',to_date('09-OCT-17','DD-MON-RR'),'PRASADR',to_date('09-OCT-17','DD-MON-RR'),'0001','BKN');
Insert into BKN_DS_PARM (CONFIG_ID,CONFIG_VAL,CONFIG_DES,IS_VARIABLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,APP_ID) values ('ACCT_LENGTH','22','Account Length','N',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'0001','BKN');
Insert into BKN_DS_PARM (CONFIG_ID,CONFIG_VAL,CONFIG_DES,IS_VARIABLE,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,BANK_CODE,APP_ID) values ('ADV_MSG','100','Marry Christmas','Y',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'0001','BKN');  

-- 20) CMN_DR_CTRY 
  CREATE TABLE CMN_DR_CTRY(
  	"CTRY_CODE" VARCHAR2(3 BYTE), 
	"NUM_CTRY_CODE" VARCHAR2(3 BYTE), 
	"CTRY_DESC" VARCHAR2(500 BYTE), 
	"SHRT_CTRY_CODE" VARCHAR2(2 BYTE), 
	"INTL_DIAL_CODE" VARCHAR2(5 BYTE), 
	"DEF_NNTY" VARCHAR2(50 BYTE), 
	"STATUS_CODE" NUMBER(3,0), 
	"ADDED_BY" VARCHAR2(30 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE), 
	"MODIFIED_DATE" DATE
   );
   
Insert into CMN_DR_CTRY (CTRY_CODE,NUM_CTRY_CODE,CTRY_DESC,SHRT_CTRY_CODE,INTL_DIAL_CODE,DEF_NNTY,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values ('BLZ','084','Belize','BZ','+501','Belizean',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'));
Insert into CMN_DR_CTRY (CTRY_CODE,NUM_CTRY_CODE,CTRY_DESC,SHRT_CTRY_CODE,INTL_DIAL_CODE,DEF_NNTY,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values ('BMU','060','Bermuda','BM','1-441','Bermudian',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'));
Insert into CMN_DR_CTRY (CTRY_CODE,NUM_CTRY_CODE,CTRY_DESC,SHRT_CTRY_CODE,INTL_DIAL_CODE,DEF_NNTY,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE) values ('BOL','068','Bolivia','BO','+591','Bolivian',1,'DATALOADER',to_date('26-OCT-11','DD-MON-RR'),'DATALOADER',to_date('26-OCT-11','DD-MON-RR'));


-- 21) BKN_DX_TRXN_TEMP
  
  CREATE TABLE BKN_DX_TRXN_TEMP(
  	"TRANSACTION_NUMBER" NUMBER(20,0), 
	"DE_2" VARCHAR2(40 BYTE), 
	"DE_3" VARCHAR2(6 BYTE), 
	"DE_4" NUMBER(16,0), 
	"DE_5" NUMBER(16,0), 
	"DE_6" NUMBER(16,0), 
	"DE_7" VARCHAR2(14 BYTE), 
	"DE_10" VARCHAR2(8 BYTE), 
	"DE_11" VARCHAR2(6 BYTE), 
	"DE_12" VARCHAR2(14 BYTE), 
	"DE_13" VARCHAR2(4 BYTE), 
	"DE_14" VARCHAR2(4 BYTE), 
	"DE_15" VARCHAR2(6 BYTE), 
	"DE_18" VARCHAR2(4 BYTE), 
	"DE_19" VARCHAR2(3 BYTE), 
	"DE_22" VARCHAR2(3 BYTE), 
	"DE_24" VARCHAR2(3 BYTE), 
	"DE_25" VARCHAR2(4 BYTE), 
	"DE_26" VARCHAR2(4 BYTE), 
	"DE_28" VARCHAR2(9 BYTE), 
	"DE_29" VARCHAR2(9 BYTE), 
	"DE_30" VARCHAR2(9 BYTE), 
	"DE_31" VARCHAR2(9 BYTE), 
	"DE_32" VARCHAR2(11 BYTE), 
	"DE_33" VARCHAR2(11 BYTE), 
	"DE_35" VARCHAR2(37 BYTE), 
	"DE_37" VARCHAR2(24 BYTE), 
	"DE_38" VARCHAR2(6 BYTE), 
	"DE_39" VARCHAR2(3 BYTE), 
	"DE_40" VARCHAR2(3 BYTE), 
	"DE_41" VARCHAR2(8 BYTE), 
	"DE_42" VARCHAR2(15 BYTE), 
	"DE_43" VARCHAR2(40 BYTE), 
	"DE_45" VARCHAR2(99 BYTE), 
	"DE_46" VARCHAR2(99 BYTE), 
	"DE_47" VARCHAR2(99 BYTE), 
	"DE_48" VARCHAR2(99 BYTE), 
	"DE_49" VARCHAR2(3 BYTE), 
	"DE_50" VARCHAR2(3 BYTE), 
	"DE_51" VARCHAR2(3 BYTE), 
	"DE_54" VARCHAR2(120 BYTE), 
	"DE_56" VARCHAR2(99 BYTE), 
	"DE_57" VARCHAR2(99 BYTE), 
	"DE_60" VARCHAR2(99 BYTE), 
	"DE_62" VARCHAR2(50 BYTE), 
	"DE_63" VARCHAR2(99 BYTE), 
	"DE_66" VARCHAR2(1 BYTE), 
	"DE_67" VARCHAR2(20 BYTE), 
	"DE_68" VARCHAR2(12 BYTE), 
	"DE_69" VARCHAR2(20 BYTE), 
	"DE_70" VARCHAR2(3 BYTE), 
	"DE_71" VARCHAR2(99 BYTE), 
	"DE_90" VARCHAR2(42 BYTE), 
	"DE_95" VARCHAR2(42 BYTE), 
	"DE_100" VARCHAR2(11 BYTE), 
	"DE_102" VARCHAR2(28 BYTE), 
	"DE_103" VARCHAR2(28 BYTE), 
	"DE_104" VARCHAR2(30 BYTE), 
	"DE_105" VARCHAR2(10 BYTE), 
	"DE_106" VARCHAR2(10 BYTE), 
	"DE_107" VARCHAR2(8 BYTE), 
	"DE_108" VARCHAR2(25 BYTE), 
	"DE_109" VARCHAR2(25 BYTE), 
	"DE_110" VARCHAR2(8 BYTE), 
	"DE_111" VARCHAR2(50 BYTE), 
	"DE_112" VARCHAR2(20 BYTE), 
	"DE_113" VARCHAR2(20 BYTE), 
	"DE_114" VARCHAR2(3 BYTE), 
	"DE_115" VARCHAR2(50 BYTE), 
	"DE_116" VARCHAR2(20 BYTE), 
	"DE_117" VARCHAR2(20 BYTE), 
	"DE_118" VARCHAR2(3 BYTE), 
	"DE_119" VARCHAR2(10 BYTE), 
	"DE_120" VARCHAR2(10 BYTE), 
	"DE_124" VARCHAR2(10 BYTE), 
	"DE_125" VARCHAR2(28 BYTE), 
	"MESSAGE_TYPE" VARCHAR2(4 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(10 BYTE), 
	"TRX_STATUS" NUMBER(2,0), 
	"OFFLINE_AUTH_ID" VARCHAR2(6 BYTE), 
	"BILLING_AMOUNT" NUMBER(16,0), 
	"SETTLEMENT_AMOUNT" NUMBER(16,0), 
	"CURR_CONVERSION_RATE" NUMBER(10,2), 
	"CURR_CONVERSION_DATE" DATE, 
	"ORIGINAL_TRX_NUMBER" NUMBER(20,0), 
	"POSTING_DATE" DATE, 
	"STATEMENT_AGE" NUMBER(10,0), 
	"TRXN_AUTH_REASON_CODE" VARCHAR2(3 BYTE), 
	"SETLMNT_DAY_COUNT" NUMBER(2,0), 
	"ADDITIONAL_FIELD1" VARCHAR2(100 BYTE), 
	"ADDITIONAL_FIELD2" VARCHAR2(100 BYTE), 
	"ADDITIONAL_FIELD3" VARCHAR2(100 BYTE), 
	"ADDITIONAL_FIELD5" VARCHAR2(100 BYTE), 
	"ADDITIONAL_FIELD6" VARCHAR2(100 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"CUST_TYP" VARCHAR2(20 BYTE), 
	"ADDED_DATE" DATE, 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"SETTLE_DATE" DATE, 
	"SETTLE_TYP" VARCHAR2(10 BYTE), 
	"BANK_CODE" VARCHAR2(10 BYTE), 
	"SETL_FLAG" NUMBER(1,0), 
	"MERC_CAT_CODE" VARCHAR2(20 BYTE), 
	"EOD_DATE" DATE
   );



-- 22) SWT_DR_BASE_TRXN_TYP

CREATE TABLE SWT_DR_BASE_TRXN_TYP(
	"TRXN_TYP" VARCHAR2(4 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"CR_DR" VARCHAR2(2 BYTE), 
	"TRXN_CAT" VARCHAR2(10 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"STMT_DES" VARCHAR2(50 BYTE), 
	"INT_FEE_TYP" VARCHAR2(100 BYTE)
   );
   
Insert into SWT_DR_BASE_TRXN_TYP (TRXN_TYP,DESCRIPTION,CR_DR,TRXN_CAT,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,STMT_DES,INT_FEE_TYP) values ('135','Payment [Flexcube]','CR','PAY',1,'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'Payment [Flexcube]',null);
Insert into SWT_DR_BASE_TRXN_TYP (TRXN_TYP,DESCRIPTION,CR_DR,TRXN_CAT,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,STMT_DES,INT_FEE_TYP) values ('194','Offline VISA Sale','DR','PCH',1,'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'Offline VISA Sale','INTEREST_FEE');
   


-- 25) 
CREATE SEQUENCE  BKN_DQ_SERVICE_RUN  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 5 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  BKN_DQ_OVER_LMT_ACCT  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1000 NOCACHE ORDER  NOCYCLE;
CREATE SEQUENCE  BKN_DQ_INT  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 6915 NOCACHE ORDER  NOCYCLE;
CREATE SEQUENCE  BKN_DQ_FILE_DET  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 100 NOCACHE  ORDER  NOCYCLE;

commit;


-- end 
   
   