SET SCHEMA IBL_D_SIM;
-- [BKN]

-- 1) Function
--		MASK_DATA - > write java function || select IBL_D_SIM.MASK_DATA('eeed') from dual
		CREATE ALIAS MASK_DATA FOR "com.interblocks.eod.controller.Functions.MASK_DATA";
		CREATE ALIAS GET_DATA FOR "com.interblocks.eod.controller.Functions.GET_DATA";
		commit;

-- 2) SWT_DR_BASE_TRXN_TYP
CREATE TABLE SWT_DR_BASE_TRXN_TYP(
	"TRXN_TYP" VARCHAR2(4 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"CR_DR" VARCHAR2(2 BYTE), 
	"TRXN_CAT" VARCHAR2(10 BYTE), 
	"STATUS_CODE" NUMBER(2,0), 
	"ADDED_BY" VARCHAR2(25 BYTE), 
	"ADDED_DATE" DATE, 
	"MODIFIED_BY" VARCHAR2(25 BYTE), 
	"MODIFIED_DATE" DATE, 
	"STMT_DES" VARCHAR2(50 BYTE), 
	"INT_FEE_TYP" VARCHAR2(100 BYTE)
   );
   
Insert into SWT_DR_BASE_TRXN_TYP (TRXN_TYP,DESCRIPTION,CR_DR,TRXN_CAT,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,STMT_DES,INT_FEE_TYP) values ('135','Payment [Flexcube]','CR','PAY',1,'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'Payment [Flexcube]',null);
Insert into SWT_DR_BASE_TRXN_TYP (TRXN_TYP,DESCRIPTION,CR_DR,TRXN_CAT,STATUS_CODE,ADDED_BY,ADDED_DATE,MODIFIED_BY,MODIFIED_DATE,STMT_DES,INT_FEE_TYP) values ('194','Offline VISA Sale','DR','PCH',1,'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'ISUITE-4',to_date('25-DEC-17','DD-MON-RR'),'Offline VISA Sale','INTEREST_FEE');
   
CREATE SEQUENCE  TEST_SEQ_K  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 100 NOCACHE  ORDER  NOCYCLE;

commit;

-- end 
   
   